method = 'sqd'
#molecule = 'N2'
molecule = 'H2O'
ansatz = 'LUCJ'
n_reps = 2
#basis='STO-3g'
#basis = 'sto3g'
basis = '631g'
#basis = 'ccpvdz'
initialization = 'ccsd'
ansatz_used = 'LUCJ'
# ansatz_used = 'ours'
#ansatz_used = 'optimized LUCJ'
#initialization = 'mp2'
#initialization = 'random_uniform'
batches = 5
iterations = 5
samples_per_batch = 1000
#bond_dist = 2.5
prob_2 = 1e-2
prob_1 = 1e-3
bond_dist =float(input())# 1.5# 1.5
t2_thresh = 1e-10
t1_thresh = 1e-10
s_thresh = 1e-10
two_body_int_thresh = 1e-10
s_t2_thresh = 1e-10
s_s_thresh = 1e-10
#n_shots = 1000000 #50000# 100000
n_shots = 250000
sampler_data_available = 'yes' #'yes'
mbpt_data_available = 'yes'
synthetic_noise = 'no'
#synthetic_noise = 'yes'
run = 100
#n_samples = n_shots# 50000
n_samples_scale_factor = 2 #30# 100# 50 #50
mbpt_max_rank = 4
en_conv_thresh =1e-5 #0.000015 #2e-5
rbm_training_iter = 3# 10# 1000# 500# 1000
n_gibbs_sampling = 1
constrained_gibbs_generation = 'yes'
projection_batch_size = 100000
parallelized_projection = 'yes'# 'no'
n_cores_for_parallel_projection = 1
use_dominant_dets_for_gibbs=False #True #False
n_hidden_factor = 1 #usually kept 1 for the paper
jw_mapped_ham_available ='yes'# 'no'
#jw_mapped_ham_available ='no'
#matrix_diagonalization_type = 'dci' #'csr'
matrix_diagonalization_type = 'csr'
cluster = 'yes'
